#???
server:
  port: 8181

spring:
  #?????
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 105293
    url: jdbc:mysql://localhost:3306/lizhi_task?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC

#mybatis-plus??
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.mzl.transaction.entity
  type-enums-package: com.mzl.transaction.enums
  # MyBatis ???????
  configuration:
    # ?????????????camel case???
    mapUnderscoreToCamelCase: true
    # ??????SQL?????????
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    # ??????SQL???????
  #    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
  # ??????
  global-config:
    db-config:
      logic-delete-field: deleted  # ????????????(since 3.3.0,????????????2)
      logic-delete-value: 0 # ??????(??? 1)
      logic-not-delete-value: 1 # ??????(??? 0)
      #???????
      select-strategy: not_empty

